language: python
cache:
  - pip
  - directories:
      - "$HOME/.pyenv"
      - "$HOME/Library/Caches/Homebrew"
      - "$HOME/.git/lfs"
notifications:
  email: false
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install flake8 jinja2 sphinx sphinx_rtd_theme
  - python setup.py build_ext --inplace
  - eval "$(ssh-agent -s)"
script:
  - pytest tests
  - flake8 ssh2
  # Test source distribution builds
  - python setup.py sdist
  - cd dist
  - pip install *
  - python -c 'from ssh2.session import Session; Session()'
  - cd ..
  - cd doc
  - make html
  - cd ..
sudo: required
dist: xenial
services:
  - docker
addons:
  apt:
    packages:
      - openssh-server
      - rpm
      - dpkg
      - cmake

jobs:
  include:

    - stage: test
      if: type = push OR \
          (type = pull_request AND fork = true)

    - &osx-wheels
      stage: build packages
      if: tag IS present
      os: osx
      osx_image: xcode11.6
      env:
        - SYSTEM_LIBSSH2: 1
      before_install:
        - brew install libssh2
        - pip3 install twine
        - which twine
      install: skip
      script:
        - ./ci/osx-wheel.sh
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload --skip-existing -u $PYPI_U -p $PYPI_P wheels/*.whl;
          fi
      language: generic
      python: skip

    - <<: *osx-wheels
      osx_image: xcode11.3

    - stage: build packages
      if: tag IS present
      os: linux
      python: 3.6
      env:
        - WHEELS=1
      install:
        - pip install twine
      script:
        - python setup.py sdist
        - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
        - ./ci/travis/build-manylinux.sh
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload --skip-existing -u $PYPI_U -p $PYPI_P wheelhouse/*.whl dist/*;
          fi
