language: python
cache:
  - pip
  - directories:
      - "$HOME/.pyenv"
      - "$HOME/Library/Caches/Homebrew"
      - "$HOME/.git/lfs"
notifications:
  email: false

jobs:
  include:

    - stage: test
      if: (type == push) OR \
          (type == pull_request AND fork == true)
      sudo: required
      dist: xenial
      services:
        - docker
      python:
        - 2.7
        - 3.6
        - 3.7
        - 3.8
      addons:
        apt:
          packages:
            - openssh-server
            - rpm
            - dpkg
            - cmake
      install:
        - pip install flake8 jinja2 sphinx sphinx_rtd_theme
        - python setup.py build_ext --inplace
        - eval "$(ssh-agent -s)"
      script:
        - pytest tests
        - flake8 ssh2
        # Test source distribution builds
        - python setup.py sdist
        - cd dist
        - pip install *
        - python -c 'from ssh2.session import Session; Session()'
        - cd ..
        - cd doc
        - make html
        - cd ..

    - &osx-wheels
      stage: build packages
      if: (type == push) OR \
          (type == pull_request AND fork == true)
      os: osx
      osx_image: xcode11.6
      env:
        - SYSTEM_LIBSSH2: 1
      before_cache:
        - brew cleanup
      before_install:
        - brew install libssh2
        - pip3 install twine
        - which twine
      install: skip
      script:
        - ./ci/osx-wheel.sh
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload --skip-existing -u $PYPI_U -p $PYPI_P wheels/*.whl;
          fi
      language: generic
      python: skip

    - <<: *osx-wheels
      osx_image: xcode11.3

    # - <<: *osx-wheels
    #   osx_image: xcode11.6
    #   env:
    #     - PYENV: 3.7.8
    #     - SYSTEM_LIBSSH2: 1
    #   install: skip
    #   script:
    #     - travis_wait ./ci/travis/pyenv-wheel.sh

    # - <<: *osx-wheels
    #   osx_image: xcode11.3
    #   env:
    #     - PYENV: 3.7.8
    #     - SYSTEM_LIBSSH2: 1
    #   install: skip
    #   script:
    #     - travis_wait ./ci/travis/pyenv-wheel.sh

    # - <<: *osx-wheels
    #   osx_image: xcode11.3
    #   env:
    #     - PYENV: 3.8.5
    #     - SYSTEM_LIBSSH2: 1
    #   install: skip
    #   script:
    #     - travis_wait ./ci/travis/pyenv-wheel.sh

    # - <<: *osx-wheels
    #   osx_image: xcode11.6
    #   env:
    #     - PYENV: 3.8.5
    #     - SYSTEM_LIBSSH2: 1
    #   install: skip
    #   script:
    #     - travis_wait ./ci/travis/pyenv-wheel.sh

    - stage: build packages
      if: tag IS present
      os: linux
      python: 3.6
      env:
        - WHEELS=1
      install:
        - pip install twine
      script:
        - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
        - ./ci/travis/build-manylinux.sh
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload --skip-existing -u $PYPI_U -p $PYPI_P wheelhouse/*.whl;
          fi
      deploy:
        - provider: pypi
          skip_cleanup: true
          on:
            repo: ParallelSSH/ssh2-python
            tags: true
          distributions: sdist
          user: pkittenis
          password:
            secure: "eEBo76bmNWArLOzLNkv8whYO81HqkYpwUu3RqBHv6PNW/sI70VSIVfPTWo8ThlNkYSBy1Sxci6eU+Vd8qYH/vaCbl4068BkzroGUqGMLHXLRLEPQjO2pxTvnQ7Nbj/Mi9enoslLJKflx2USy2iPz1yGCWZrPzjLWmEMcx6j5e3fEUGF2p6p01w/zWxmiSoyJgBsby9P8Fl5nflsNMVR/or8frK4K1T6Y2oTuEx9aYymmBPFOO5DHaedDxnhZ04KKaACIECvKrT5V3PMM1jrE3qu6hJ1LS0/mSivEdCwCszHanjIQy/enkNtLgxVm4jIRUjuAwL1MmxPtkAUcKrQor1YokMqm5fExdwvnp+qjtyejfA3IvT93nYvCj4IEYNMDtUGFUBjsYLqg7Ked/jvO53Ek5WEAE/Mx8F/OAtuvkpEeUKTIWxfd+V0b7pgShVuU5zFyi3y97vpRtdwqzOFr8QT3Hq+g/RIdghPQ9pGQ3GOomTMO1B7mAyOG6SYyQM/wra2h2dQTHCbgzAtsPzZLiZhWIGcU7/mGLm0kZBT6McnH2//hsIPXG8S94u2MWE0KRH5YhJ/2ATWneYyFHWQfwqDeR/1CZe66gFcPJ9cOIG+8pcmXueLhnueDbh2EWa8jmumtrAz+z+rcokih0c7catT7pByDv24Ouuw2Yf3my60="
